steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/project-af859b35-b479-403a-9fb/cloud-run-source-deploy/mle/mle:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/project-af859b35-b479-403a-9fb/cloud-run-source-deploy/mle/mle:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "mle"
      - "--image"
      - "us-central1-docker.pkg.dev/project-af859b35-b479-403a-9fb/cloud-run-source-deploy/mle/mle:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "${_PLATFORM}"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2"
      - "--timeout"
      - "300"

images:
  - "us-central1-docker.pkg.dev/project-af859b35-b479-403a-9fb/cloud-run-source-deploy/mle/mle:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
